# Generated by Django 5.2.8 on 2025-11-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
