# Generated by Django 5.2.8 on 2025-11-25 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_practicetask_userpracticetask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPracticeTask',
            new_name='UserTask',
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='practicetask',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('user', 'task')},
        ),
    ]
