# Generated by Django 5.2.8 on 2025-11-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_skill_difficulty_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
