# Generated by Django 5.2.8 on 2025-12-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='session_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
    ]
