# Generated by Django 5.2.8 on 2025-12-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_skillmaterial_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
